
name: Test and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js ${ { matrix.node-version } }
      uses: actions/setup-node@v4
      with:
        node-version: ${ { matrix.node-version } }
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
  
  security-test:
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Security test
      run: npm audit
